### ISSUE TITLE
New verification method in summon selection during GW

### ISSUE THREAD

**Issue by Frizz925** [Frizz925/gbf-autopilot-core#15]
Although this can be solved much more easily than regular captchas, these verifications seem to appear more often than the usual captcha (2-3 hours run can trigger verification compared to 4-6 hours using the old captcha).

What's more, most bots that aren't updated yet won't see this new verification button and the game put 1 summon in supporter page as some sort of "bot bait" since most bots would just see that the summon selection is actually there (although incomplete).

**Comment by Frizz925** [comment]
This is pretty clever actually. Anyone who's using the bot for GW should take this verification with care.

**Comment by pannatatm** [comment]
I want to confirm about what behavior bot do if that pages appear. If it continuing selecting summon that would raise huge ban flag. But if the bot stop that would be very fine. As I'm using geasemonkey script to detect all div that contain word "Verify" and make an alert sound if it found.

**Comment by Frizz925** [comment]
The bot would still click the "bait". This is caused by the old summon selection behavior when no preferred summon is found, the bot would select any available summon randomly. In the case of summon chosen is not the preferred summon while the reroll option is enabled, the bot would still click it because it thinks the preferred summon is already available from the trial battle page.

**Comment by Frizz925** [comment]
Implementing the verification checker is time-consuming as it takes some time for the verification button to appear. I'll implement a workaround for the detection by checking if the number of available summons in summon selection (supporter) page is unusually less than usual (eg. only less than 5 summons available).

**Comment by pannatatm** [comment]
But it seem you would trigger ban if you spamming 'bait' button for multiple times. Which is Z bot behavior. Autopilot only click it once and wait for party selection to appear so it pretty safe. Otherwise normal player who misclick 1 time will get banned from it too.

**Comment by Frizz925** [comment]
Actually, ever since commit https://github.com/Frizz925/gbf-autopilot-core/commit/a9abd56f10c7edd2f12542269156c14a0badd937 the bot would "spam" click the summon button since even under the normal circumstances, clicking the summon selection once will sometimes not show the party selection popup and thus causing the bot to get stuck.

Due to high frequency of this verification, it's best to not use the bot at all at this time until this issue has been addressed.

**Comment by pannatatm** [comment]
Oh, I haven’t update to lastest version yet so I just miraclly avoided from ban lol. I think it better to just click summon only just 2-3 times and if the party select not come up usually the page is broken and no matter how many times you click it it won’t show up and need to refresh anyway. I’m pretty sure cygame going to make more different bait so make the bot play as human like as possible.

Different question but do lastest version bot have built-in function to detect original captcha yet? I think just using filter to find some keyword (like div:contain(automat)) that will stop the bot and alert user could fix problem for time being.

**Comment by Frizz925** [comment]
Not yet. If you use some sort of userscript or knows the unique CSS selector to detect the old captcha then it would be a great help to post it here (as in open a new issue for future enhancement).

And about "broken page", I have not considered making it yet. I thought it's mostly just UI bug that requires the button to be clicked multiple times before the event emitter actually fires.

**Comment by Frizz925** [comment]
Workaround implemented. Check the [wiki page](https://github.com/Frizz925/gbf-autopilot/wiki/%5BUpdate-2018-02-16%5D-Captcha:-Summon-Verify) for details.

**Comment by Homusamu** [comment]
@Frizz925 I managed to copy the verification page script. It is not appear to me but the script do load in summon page so I found it while playing around with my userscript.

```
<script type="text/html" id="tpl-prt-summon-list-lobby">
		<% _.each(list, function(attributeSupporterList, index){ %>
			<div class="prt-supporter-attribute<% if((index) !== 2 && !(1 > 2 || 6 < 2) ){ %> disableView<% } %>">
				<% _.each(attributeSupporterList, function(supporterData){ %>
					<div class="btn-supporter lis-supporter" data-viewer-id="<%= supporterData.viewer_id %>" data-supporter-user-id="<%= supporterData.user_id %>" data-face="<%= supporterData.job_image %>" data-last-login="" data-attribute="<%= supporterData.attribute_key %>" data-supporter-max="<%= !supporterData.pc_summon_1_evolution_flag ? 1 : 0 %>" data-supporter-evolution="<%= supporterData.pc_summon_1_evolution %>">
						<div class="prt-supporter-name<% if(supporterData.is_friend === true){ %> ico-friend<% } %>"><span class="txt-supporter-name"><%= supporterData.nick_name %></span> <span class="txt-supporter-level">Rank <%= supporterData.level %></span></div>
						<div class="prt-supporter-info">
							<div class="prt-summon-image" data-image="<%= supporterData.pc_summon_1 %>">
								<img class="img-supporter-summon" src="http://game-a.granbluefantasy.jp/assets_en/img_light/sp/assets/summon/m/<%= supporterData.pc_summon_1 %>.jpg">
								<% if(supporterData.pc_summon_1_quality > 0){ %><div class="prt-summon-quality">+<%= supporterData.pc_summon_1_quality %></div><% } %>
							</div>
							<div class="prt-supporter-detail">
								<% if(!supporterData.pc_summon_1_evolution_flag){ %><div class="prt-summon-max"></div><% } %>
								<div class="prt-supporter-summon">
									<span class="txt-summon-level">Lvl <%= supporterData.pc_summon_1_level %></span> <%= supporterData.pc_summon_1_name %>
								</div>
								<div class="prt-summon-skill<% if(supporterData.pc_summon_1_skill_comment.length > 21){ %> text-small<% } %><% if(+supporterData.pc_summon_1_evolution === 3){ %> bless-rank1-style<% }else if(supporterData.pc_summon_1_evolution >= 4){ %> bless-rank2-style<% } %>"><%= supporterData.pc_summon_1_skill_comment %></div>
							</div>
						</div>
						<div class="prt-supporter-thumb">
							<img class="img-supporter" src="http://game-a.granbluefantasy.jp/assets_en/img_light/sp/assets/leader/a/<%= supporterData.job_image %>.png">
						</div>
						<div class="prt-button-cover"></div>
					</div>
				<% }); %>
				
				<% if (is_supporter_caution === true) { %>
					<div class="prt-supporter-confirm">
	<div class="prt-module-inner-title">Please Verify</div>
		<div class='txt-supporter-confirm-en'>Please tap the button below to verify that you're not using any automated tools. The complete support summon list will be displayed after verification.</div>
	<div class="btn-supporter-confirm">Verify</div>
</div>
				<% } %>
			</div>
		<% }); %>
	</script>
				<% } %>
			</div>
		<% }); %>
	</script>
```

Your method of detecting also work well but this can be useful as reference I think :)

**Comment by Frizz925** [comment]
Whoa, nice find. But I'm not sure if they'll keep the current kind of verification since this is way too easy to be solved by bots. Let's just watch and see if they introduce any new kind of detection countermeasures.
